<!doctype html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            
                Výjimky
            
        </title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/nausce.css">
        <link rel="stylesheet" href="/static/css/body.css">
        <link rel="stylesheet" href="/static/css/pygments-lovelace-style.css">
        

        
        

        <style>
            
    
        .err-lineno {
    display: inline-block;
    background-color: #DFF;
}

    

        </style>
    </head>
    
    <body>
        
        <nav class="header">
            <ul class="container menu">
                <li><a href="/" class="logo"><h1>Nauč se Python!</h1></a></li>
                <li><a href="/courses/" class="menu-link"><h2>Materiály</h2></a></li>
                <li><a href="/runs/" class="menu-link"><h2>Kurzy</h2></a></li>
            </ul>
        </nav>
        

        
            <div class="content">
                <div class="alert alert-danger" role="alert">
                    Tato stránka je momentálně v rekonstrukci.
                    Pokud se chcete podílet na vylepšování těchto stránek,
                    navštivte repozitář na
                    <a href="https://github.com/pyvec/naucse.python.cz">GitHubu</a>.
                </div>
            </div>
        

        

<div class="page">
    <div class="container">

        

        
            
<div class="slides row stuff">
                <section class="col-lg-12">
                    <section>
                        <h1>Výjimky</h1>
                        <p>
                            Výjimky už známe: Python si postěžuje, řekne kde
                            je chyba, a ukončí program.
                            To ale není všechno, co výjimky umí.
                            Pojďme si o nich ukázat něco víc.
                        </p>
                    </section>
                    <section>
                        <h2>Výpisy chyb</h2>
                        <div>
                            Na začátku si ukážeme (nebo zopakujeme),
                            jak se vypisuje chyba, která nastane v zanořené
                            funkci:
                        </div>
<pre>
def vnejsi_funkce():
    return vnitrni_funkce(0)

def vnitrni_funkce(delitel):
    return 1 / delitel

print(vnejsi_funkce())
</pre>

<pre>
Traceback (most recent call last):          
  File "/tmp/ukazka.py", line <span class="err-lineno">7</span>, in &lt;module&gt;
    print(vnejsi_funkce())
  File "/tmp/ukazka.py", line <span class="err-lineno">2</span>, in vnejsi_funkce
    return vnitrni_funkce(0)
  File "/tmp/ukazka.py", line <span class="err-lineno">5</span>, in vnitrni_funkce
    return 1 / delitel
ZeroDivisionError: division by zero
</pre>

                        <div>
                            Všimni si, že každá funkce, jejíž volání vedlo
                            k chybě, je uvedena ve výpisu.
                            Skutečná chyba (tedy místo, které musíme opravit)
                            je pravděpodobně poblíž některého z těchto volání.
                            V našem případě bychom asi neměly volat
                            <code>vnitrni_funkce</code> s argumentem
                            <code>0</code>. A nebo by
                            <code>vnitrni_funkce</code> měla být na nulu
                            připravená a dělat v tomto případě něco jiného.
                        </div>
                    </section>
                    <section>
                        <h2>Vyvolání chyby</h2>
                        <div>
                            Chybu neboli <em>výjimku</em>
                            (angl. <em>exception</em>) můžeme vyvolat i samy,
                            pomocí příkazu <code>raise</code>.
                            Za příkaz dáme jméno výjimky, a pak do závorek
                            nějaký popis toho, co je špatně.
                        </div>
<pre>
VELIKOST_POLE = 20

def over_cislo(cislo):
    if 0 &lt;= cislo &lt; VELIKOST_POLE:
        print('OK!')
    else:
        raise ValueError('Čislo {n} není v poli!'.format(n=cislo))
</pre>
                        <div>
                            Všechny typy výjimek, které jsou zabudované
                            v Pythonu, jsou popsané
                            <a href="https://docs.python.org/3.2/library/exceptions.html#exception-hierarchy">
                                v dokumentaci.
                            </a>
                            Pro nás jsou (nebo budou) důležité tyto:
                        </div>
<pre>
BaseException
 ├── SystemExit                     vyvolána funkcí exit()
 ├── KeyboardInterrupt              vyvolána po stisknutí Ctrl+C
 ╰── Exception
      ├── ArithmeticError
      │    ╰── ZeroDivisionError    dělení nulou
      ├── AssertionError            nepovedený příkaz `assert`
      ├── AttributeError            neexistující atribut, např. 'abc'.len
      ├── ImportError               nepovedený import
      ├── LookupError
      │    ╰── IndexError           neexistující index, např. 'abc'[999]
      ├── NameError                 použití neexistujícího jména proměnné
      │    ╰── UnboundLocalError    použití proměnné, která ještě nebyla nastavená
      ├── SyntaxError               špatná syntaxe – program je nečitelný/nepoužitelný
      │    ╰── IndentationError     špatné odsazení
      │         ╰── TabError        kombinování mezer a tabulátorů
      ├── TypeError                 špatný typ, např. len(9)
      ╰── ValueError                špatná hodnota, např. int('xyz')
</pre>
                    </section>
                    <section>
                        <h2>Ošetření chyby</h2>
                        <p>
                            A proč jich je tolik druhů?
                            Abychom je mohly chytat!
                            Následující program je připravený na to, že
                            funkce <code>int</code> může selhat, pokud
                            uživatel nezadá číslo:
                        </p>
<pre>
def nacti_cislo():
    odpoved = input('Zadej číslo: ')
    try:
        cislo = int(odpoved)
    except ValueError:
        print('To nebylo číslo!')
</pre>
                        <div>
                            Pokud odchytáváme obecnou výjimku,
                            chytnou se i všechny podřízené typy výjimek
                            – například <code>except ArithmeticError:</code>
                            zachytí i <code>ZeroDivisionError</code>.
                            A <code>except Exception:</code> zachytí všechny
                            výjimky, které běžně chceme zachytit.
                        </div>
                    </section>
                    <section>
                        <h2>Nechytej je všechny!</h2>
                        <div>
                            Většinu chyb není potřeba ošetřovat.
                        </div>
                        <div>
                            Nastane-li nečekaná situace, je téměř vždy
                            <em>mnohem</em> lepší program ukončit, než se snažit
                            pokračovat dál počítat se špatnými hodnotami.
                            Navíc chybový výstup který Python standardně
                            připraví, může hodně ulehčit hledání chyby.
                        </div>
                        <div>
                            „Ošetřování” chyb jako <code>KeyboardInterrupt</code>
                            je ještě horší: může způsobit, že program nepůjde
                            ukončit, když bude potřeba.
                        </div>
                        <div>
                            Příkaz <code>try/except</code> proto používej
                            jen v situacích, kdy víš přesně která chyba může
                            nastat a proč, a máš možnost ji opravit.
                            Pro nás to typicky bude načítání vstupu
                            od uživatele, kdy máme po špatném pokusu
                            o zadání možnost zeptat se znovu.
                        </div>
                    </section>
                    <section>
                        <h2>Další přílohy k <code>try</code></h2>
                        <div>
                            Kromě <code>except</code> existují dva jiné bloky,
                            které k <code>try</code> můžeme přilepit:
                            <code>else</code> a <code>finally</code>.
                            První se provede když v <code>try</code> bloku
                            žádná chyba nenastane; druhý se provede vždy – ať
                            už chyba nastala nebo ne.
                        </div>
<pre>
try:
    neco_udelej()
except ValueError:
    print('Tohle se provede, pokud nastane ValueError')
except NameError:
    print('Tohle se provede, pokud nastane NameError')
except Exception:
    print('Tohle se provede, pokud nastane jiná chyba')
    # (kromě SystemExit a KeyboardInterrupt, ty chytat nechceme)
else:
    print('Tohle se provede, pokud chyba nenastane')
finally:
    print('Tohle se provede vždycky; i pokud v `try` bloku byl např. `return`')
</pre>
                    </section>
                    <section>
                        <h2>Úkol</h2>
                        <div>
                            Doplň do 1-D piškvorek ošetření chyby, která
                            nastane když uživatel nezadá číslo.
                        </div>
<details class="solution notes"><h3>Řešení</h3>
<pre>
def tah_hrace(pole):
    while True:
        try:
            pozice = int(input('Kam chceš hrát? (0..19) '))
        except ValueError:
            print('To není číslo!')
        else:
            if pozice &lt; 0 or pozice >= len(pole):
                print('Nemůžeš hrát venku z pole!')
            elif pole[pozice] != '-':
                print('Tam není volno!')
            else:
                break

    pole = pole[:pozice] + 'o' + pole[pozice + 1:]
    return pole


print(tah_hrace('-x----'))
</pre>
</details>
                    </section>
                </section>
            </div>
        

        <hr class="lesson-end">

        

        

    </div>
</div>



        <script type="text/javascript" src="/static/js/solutions.js"></script>

        
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h2>Kontakt</h2>
                        <p>
                            E-mail: <a href="mailto:info@pyvec.org">info@pyvec.org</a><br>
                            GitHub: <a href="http://github.com/pyvec">github.com/pyvec</a><br>
                            Twitter: <a href="http://twitter.com/pyvec">@pyvec</a><br>
                            Youtube: <a href="http://www.youtube.com/pyvec">www.youtube.com/pyvec</a>
                        </p>
                    </div>
                    <div class="col">
                        <h2>Zapoj se</h2>
                        <p>
                            Tyto stránky na <a href="https://github.com/pyvec/naucse.python.cz">GitHubu</a>
                            <br>
                            Organizuj <a href="http://pyladies.cz/stan_se/">PyLadies</a>
                        </p>
                    </div>
                    <div class="col">
                        <h2>Licence</h2>
                        <p>
                            <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    </body>
</html>